INSERT INTO role VALUES (1,'ROLE_ADMIN');
INSERT INTO role VALUES (2,'ROLE_USER');
INSERT INTO chat_user VALUES ('admin', 'admin@jorgeacetozi.com.br', 'Jorge Acetozi', '$2a$06$WfXHoFhYT/cXcyNOZQsjMuXRyydgcUTMJcMweF0m8RMub2HS1rCHu');
INSERT INTO chat_user VALUES ('kris', 'kris@gmail.com', 'Chuck Kris', '$2a$10$UcRWWl6rDh/yk5r4Ev7s4up6fy1yvN.daAwslOzbEP.KjhlWWDCa.');
INSERT INTO chat_user VALUES ('jack', 'jack@gmail.com', 'Jack Sparrow', '$2a$10$LeFJa7UjjR7VNDmwPma.kOqeOhAmjUcqHjUEY96gyg24x4ShVQ3W6');
INSERT INTO chat_user VALUES ('alice', 'alice@gmail.com', 'Alice Spar', '$2a$10$IVL9gzcLSXppUtV61ip/y.mb7HGS4ywgX1Qt0QXHDRiz/WJgBKxkS');
INSERT INTO user_role VALUES ('admin', 1);
INSERT INTO user_role VALUES ('kris', 2);
INSERT INTO user_role VALUES ('jack', 2);
INSERT INTO user_role VALUES ('alice', 2);
